(******************************************************************************)
(*                                                                            *)
(*                  Domesday Book: Norman Tenure Well-Foundedness             *)
(*                                                                            *)
(*     Formalization of the feudal tenure graph from the Domesday survey:     *)
(*     all land held ultimately from the Crown, forming a well-founded tree   *)
(*     with no cycles. Models tenants-in-chief, subinfeudation chains, and    *)
(*     mesne lordship. Proves acyclicity rooted at William I.                 *)
(*                                                                            *)
(*     "So narrowly did he have it investigated, that there was not a         *)
(*      single hide nor yard of land, nor one ox nor cow nor pig left         *)
(*      out, and not put down in his record."                                 *)
(*     - Anglo-Saxon Chronicle, 1085                                          *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 6, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
