(******************************************************************************)
(*                                                                            *)
(*                  Domesday Book: Norman Tenure Well-Foundedness             *)
(*                                                                            *)
(*     Formalization of the feudal tenure graph from the Domesday survey:     *)
(*     all land held ultimately from the Crown, forming a well-founded tree   *)
(*     with no cycles. Models tenants-in-chief, subinfeudation chains, and    *)
(*     mesne lordship. Proves acyclicity rooted at William I.                 *)
(*                                                                            *)
(*     "Veez mei! Jo sui vif, e, Deu aidant, jo vencerai!"                    *)
(*     - William the Conqueror, 1066                                          *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 6, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
